---
site_name: pyrosimple
site_url: https://kannibalox.github.io/pyrosimple/
repo_url: https://github.com/kannibalox/pyrosimple
nav:
  - Home: index.md
  - Quick Start: quickstart.md
  - User Guide:
      - rtxmlrpc: usage-rtxmlrpc.md
      - rtcontrol: usage-rtcontrol.md
      - pyrotorque: usage-pyrotorque.md
      - "mktor/lstor/chtor": usage-tor.md
  - How-tos:
      - Changing announce URLs: changing-announce.md
      - Integrate with Conky: conky.md
      - General maintenance tasks: maintenance-tasks.md
      - Pyrotorque tutorial: pyrotorque-tutorial.md
  - Reference:
      - Configuration: configuration.md
      - Torque Jobs: pyrotorque-jobs.md
  - Advanced:
      - rTorrent Setup: rtorrent-config.md
      - Experimental Features: experimental.md
      - Tips & Tricks: tips.md
      - Migrating from pyrocore: migrate.md
      - Custom Code: custom-code.md
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - toc.integrate
  font:
    code: Inconsolata
    text: Lato
  icon:
    logo: fontawesome/regular/sun
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
plugins:
  - search
  - include-markdown
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
