[tool.poetry]
name = "pyrocore"
version = "1.0.0"
description = ""
authors = ["kannibalox <kannibalox@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
Tempita = "^0.5.2"
"bencode.py" = "^4.0.0"

[tool.poetry.group.dev.dependencies]
black = "^21.9-beta.0"

[tool.poetry.scripts]
rtxmlrpc = "pyrocore.scripts.rtxmlrpc:run"
rtcontrol = "pyrocore.scripts.rtcontrol:run"
lstor = "pyrocore.scripts.lstor:run"
mktor = "pyrocore.scripts.mktor:run"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
